sudo: false
language: node_js

env:
  - SENECA_VER=@1.x.x
  - SENECA_VER=@2.x.x
  - SENECA_VER=@3.x.x

node_js:
  - v6
  - v5
  - v4

before_script:
  - npm uninstall seneca
  - npm install seneca$SENECA_VER

cache:
  directories:
    - node_modules
